package com.codecrafter8.nl2sql.controller;

import com.codecrafter8.nl2sql.dto.LlmResponse;
import com.codecrafter8.nl2sql.service.llm.OpenAIProvider;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
class QueryControllerIT {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private VectorStore vectorStore;

    @MockBean
    private OpenAIProvider openAIProvider;

    @Test
    @DisplayName("Should execute valid SQL and return the result")
    void shouldProcessQueryAndReturnResultsEndToEnd() throws Exception {
        String simulatedSql = "SELECT COUNT(*) AS total FROM nurse";
        LlmResponse llmMock = LlmResponse.builder()
                .sql(simulatedSql)
                .promptTokens(12)
                .completionTokens(8)
                .analysis("Analysis")
                .build();
        when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

        String requestJson = """
                {
                  "naturalLanguageQuery": "Ile mamy pielęgniarek?",
                  "explainSql": false,
                  "maxRows": 100,
                  "schemaContextMode": "FULL_SCHEMA"
                }
                """;

        mockMvc.perform(post("/api/v1/query/execute")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestJson))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("SUCCESS"))
                .andExpect(jsonPath("$.generatedSql").value(simulatedSql))
                .andExpect(jsonPath("$.results").isArray())
                .andExpect(jsonPath("$.results").isNotEmpty())
                .andExpect(jsonPath("$.results[0].total").exists())
                .andExpect(jsonPath("$.rowCount").value(1));
    }

    @Test
    @DisplayName("Should block destructive SQL generated by the LLM")
    void shouldReturnErrorWhenLlmGeneratesDestructiveSql() throws Exception {
        String maliciousSql = "DROP TABLE patient";
        LlmResponse llmMock = LlmResponse.builder()
                .sql(maliciousSql)
                .promptTokens(10)
                .completionTokens(5)
                .analysis("Attempted destructive query")
                .build();
        when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

        String requestJson = """
                {
                  "naturalLanguageQuery": "Usuń pacjentów",
                  "explainSql": false,
                  "maxRows": 100,
                  "schemaContextMode": "FULL_SCHEMA"
                }
                """;

        mockMvc.perform(post("/api/v1/query/execute")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestJson))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.status").value("INVALID_SQL"))
                .andExpect(jsonPath("$.error").value("Generated SQL failed safety validation"));
    }

    @Nested
    @DisplayName("SQL Validation - Negative Testing (Antywzorce)")
    class SQLValidationNegativeTest {

        @Nested
        @DisplayName("DQL Restrictions - Operacje odczytu")
        class DQLRestrictionsIT {

            @Test
            @DisplayName("✓ Should accept SELECT query")
            void shouldAcceptValidSelect() throws Exception {
                // Updated to use existing column `Registered` from schema instead of non-existing `active`
                String validSql = "SELECT * FROM nurse WHERE Registered = 1";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(validSql)
                        .promptTokens(15)
                        .completionTokens(10)
                        .analysis("Valid SELECT")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż wszystkich aktywnych pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isOk())
                        .andExpect(jsonPath("$.status").value("SUCCESS"))
                        .andExpect(jsonPath("$.generatedSql").value(validSql));
            }

            @Test
            @DisplayName("✓ Should accept WITH (CTE) query")
            void shouldAcceptCTEQuery() throws Exception {
                // Use existing column `Registered` instead of non-existing `status`
                String validSql = "WITH active_nurses AS (SELECT * FROM nurse WHERE Registered = 1) SELECT * FROM active_nurses";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(validSql)
                        .promptTokens(20)
                        .completionTokens(15)
                        .analysis("Valid CTE")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż aktywnych pielęgniarki używając CTE",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isOk())
                        .andExpect(jsonPath("$.status").value("SUCCESS"));
            }

            @Test
            @DisplayName("✗ Should reject query not starting with SELECT or WITH")
            void shouldRejectInvalidStartOfQuery() throws Exception {
                String invalidSql = "FROM nurse SELECT *";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(invalidSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Invalid query start")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }
        }

        @Nested
        @DisplayName("DDL/DML Blocking - Operacje modyfikacji")
        class DDLDMLBlockingIT {

            @Test
            @DisplayName("✗ Should block DELETE statement")
            void shouldBlockDelete() throws Exception {
                String maliciousSql = "DELETE FROM nurse WHERE id = 1";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Delete attempt")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Usuń pielęgniarza",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block TRUNCATE statement")
            void shouldBlockTruncate() throws Exception {
                String maliciousSql = "TRUNCATE TABLE nurse";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Truncate attempt")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Wyczyść tabelę pielęgniarek",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block ALTER TABLE statement")
            void shouldBlockAlterTable() throws Exception {
                String maliciousSql = "ALTER TABLE nurse ADD COLUMN secret_column INT";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("ALTER attempt")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Dodaj kolumnę do tabeli",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block UPDATE statement")
            void shouldBlockUpdate() throws Exception {
                String maliciousSql = "UPDATE nurse SET salary = 999999 WHERE id = 1";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Update attempt")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Zaktualizuj pensję",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block INSERT statement")
            void shouldBlockInsert() throws Exception {
                String maliciousSql = "INSERT INTO nurse (name) VALUES ('Hacker')";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Insert attempt")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Dodaj pielęgniarza",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block CREATE TABLE statement")
            void shouldBlockCreateTable() throws Exception {
                String maliciousSql = "CREATE TABLE admin (username VARCHAR(100), password VARCHAR(100))";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Create attempt")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Stwórz nową tabelę",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block DROP TABLE with SELECT prefix (Statement chaining)")
            void shouldBlockDropAfterSelect() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; DROP TABLE patient";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Chained DROP")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki i usuń pacjentów",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block DELETE with SELECT prefix (Statement chaining)")
            void shouldBlockDeleteAfterSelect() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; DELETE FROM patient WHERE 1=1";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Chained DELETE")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki i usuń pacjentów",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block GRANT statement")
            void shouldBlockGrant() throws Exception {
                String maliciousSql = "GRANT SELECT ON nurse TO attacker";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Grant attempt")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Daj uprawnienia",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block REVOKE statement")
            void shouldBlockRevoke() throws Exception {
                String maliciousSql = "REVOKE SELECT ON nurse FROM admin";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Revoke attempt")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Usuń uprawnienia",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }
        }

        @Nested
        @DisplayName("SQL Injection Protection - Ochrona przed wstrzykiem SQL")
        class SQLInjectionProtectionIT {

            @Test
            @DisplayName("✗ Should block single-line comments (--)")
            void shouldBlockSingleLineComment() throws Exception {
                String maliciousSql = "SELECT * FROM nurse WHERE id = 1; -- DROP TABLE patient";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Comment injection")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarza o id 1",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block multi-line comments start (/*)")
            void shouldBlockMultiLineCommentStart() throws Exception {
                String maliciousSql = "SELECT * FROM nurse /* DELETE FROM patient */ WHERE Registered = 1";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Multi-line comment injection")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż aktywnych pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block multi-line comments end (*/)")
            void shouldBlockMultiLineCommentEnd() throws Exception {
                String maliciousSql = "SELECT * FROM nurse */ WHERE id = 1";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Comment end injection")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarza",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block extended stored procedures (xp_)")
            void shouldBlockExtendedStoredProcedures() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; EXEC xp_cmdshell 'dir'";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Extended proc injection")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block system stored procedures (sp_)")
            void shouldBlockSystemStoredProcedures() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; sp_executesql";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("System proc injection")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block EXEC dynamic execution")
            void shouldBlockExecDynamicExecution() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; EXEC('DROP TABLE patient')";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("EXEC injection")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block EXECUTE dynamic execution")
            void shouldBlockExecuteDynamicExecution() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; EXECUTE sp_stored_procedure";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("EXECUTE injection")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block comment with various whitespace patterns")
            void shouldBlockCommentWithWhitespace() throws Exception {
                String maliciousSql = "SELECT * FROM nurse;  \t  -- DROP TABLE";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("Comment with whitespace")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block case-insensitive xp_ procedures")
            void shouldBlockXpCaseInsensitive() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; XP_CMDSHELL 'malicious_code'";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("XP case insensitive")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block case-insensitive sp_ procedures")
            void shouldBlockSpCaseInsensitive() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; SP_EXECUTESQL";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("SP case insensitive")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block case-insensitive EXEC")
            void shouldBlockExecCaseInsensitive() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; eXeC('DROP TABLE')";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("EXEC case insensitive")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }

            @Test
            @DisplayName("✗ Should block case-insensitive EXECUTE")
            void shouldBlockExecuteCaseInsensitive() throws Exception {
                String maliciousSql = "SELECT * FROM nurse; eXeCuTe('code')";
                LlmResponse llmMock = LlmResponse.builder()
                        .sql(maliciousSql)
                        .promptTokens(10)
                        .completionTokens(5)
                        .analysis("EXECUTE case insensitive")
                        .build();
                when(openAIProvider.generateSQL(anyString(), anyString())).thenReturn(llmMock);

                String requestJson = """
                        {
                          "naturalLanguageQuery": "Pokaż pielęgniarki",
                          "explainSql": false,
                          "maxRows": 100,
                          "schemaContextMode": "FULL_SCHEMA"
                        }
                        """;

                mockMvc.perform(post("/api/v1/query/execute")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                        .andExpect(status().isBadRequest())
                        .andExpect(jsonPath("$.status").value("INVALID_SQL"));
            }
        }
    }
}
